travis:
  secure:
    BINSTAR_TOKEN: W6kPUHQf0GRv9siPdRvoET5gHcQOWXqkELd0Thxt6d53F/DT7Bekmy8Jr1XKPWedptIa6o5ekUolgLOC3VTJmen9EQD42MMV2E8PeLNXXVz8G+qMGWQXSeGz1faUl/DqyMQzUNYLZCkeOFoD+GE9Ba1fDD/ad3fmqaWESrZFeSZXCPZQRm4vNjgs2Jw+FfA6WmBLmSiLAcWonIHQFRBMHXlH81kL7ZozOcA9Uc0xpkiQFlYEtmyQ8vsaRdmjqo4NHpxOTUlqA1nHpaj0BGgsJbi0/ZVqbNIeIYboDZaB3mZ567/mBIRsyIguU06wQVhQGDfXCrmNh7AC1H5oTLJhG3NowyRaz5TmOWQ9hl83CDtugBds2x5Ro1Wmvr7kiZkkIqh1klOKjWCwQId+CBAoEfNPlH6wL/yVkLniwfVHRdzIDEaQWVu4+O5iogY2Pzj+OjQTlVnW5Vw5n/CI5msckhk+6BR0y/i0NItRVaRKDR0hJF9pnKXGxqp7Kk9COWfpCI/g9f5yc2h+QD7iSpauK+kypSY8fDPCMusEpnww5AAhMebfZTC4c0aXmlSo5a6RLaOaRwHfaiyyQL9isQS+s0LfEpRPfq42vU9OClo08VOno5W9gvoQP/rlhsK1TpBOvsmg5TlcAEDZGsopiHYw/FOBY5i7WT+pKzuy6o79IQc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
