travis:
  secure:
    BINSTAR_TOKEN: HIqBw++eOGe+NJ23Db1YIz2D6QruUwA6liaw6ebDnvjVRdTJy8ZG6Lh5etWh13DaVkIlheWogM9iq/5vZBTPSIPvysV2yutQw+nZtzs10pEuL7G4dEkjEI45d3ulSecozzNK74zWy77lxqTzT4FhPEctKAc/r59IFCdw3tYQDlph94p2wSZ2MNUW5MxDuo1kuN6sl5jJu7LfXURDKhkuYdVz+2y+wuyXsvno+11g/xPyNqjztPPJ82AR3RtaMiTTOyMa6N9zUevYeuchGEcnBEcFcllYq3gdUdrYjQAtEp4aWMptq/2XERmNjt8jlVvJ5Sma/uCtu26STNiMsJEvTU6hJ5TH004FK/F85oD6829T219BcqhRe2pf8f1fUdyzvJwWFUQ4M4ovbN0EeJUe/FlcTOvl3HvEAa5Xok6TAOYM+rg+xEdofYgckRdp+XZ7xvaeG2lo5XnYhcGovtd3yU65A96IXwwqCzP+TLXCvTzqHDExydhg8yxAjTVRYKC7z4OgoKIjxcfsEB16NarrbBqTbiJpd7eXelc2zvGgdDlCciOZTkBAU0AzjZWw8qhY1UyZS7eB75MmMxna40vJVpN/r3LWwPHDZQirpCu1fzlt5CBGXR59kGOVx9Bam64tmQNnltjYS+DaZbaVjV1Qhtjbtn2HBT0t/LMD2BTmja0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
